# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Release CI/CD

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11.x"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.8"
          channel: 'stable'

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Start release build
        run: flutter build ipa
